<?php


class events_widget extends WP_Widget {
	public function __construct() {
		$widget_options = array(
			'classname' => 'event_widget',
			'description' => 'Events Widget',
		);
		parent::__construct( 'event_widget', 'Events Widget', $widget_options );
	}

	public function form( $instance ) {
		return parent::form( $instance ); // TODO: Change the autogenerated stub
	}

	public function widget( $args, $instance) { ?>
	<form method="get">
		<p><label><input type="text" name="status" placeholder="Event status"/></p>
		<p><label><input type="text" name="records_number" placeholder="Number of records"/></p>
		<p><button type="submit">Submit</button></p>
	</form>

<?php
		$query_args = array(
			'post_type' => 'events',
			'meta_query' => array(
				array(
					'key' => 'events-status',
					'value' => $_GET['status'] ?? 'open',
				),
		));
		$the_query = new WP_Query( $query_args );
		if ( $the_query->have_posts() ) {
			global $post;
			$total = $the_query->post_count;
			if(($_GET['records_number'] ?? 1)  >= $total) {
				$total_records = $total;
			}
			else {
				$total_records = ($_GET['records_number'] ?? 1);
			}
			for($i = 0; $i < $total_records; $i++){
				$the_query->the_post();
				echo '<li>' . get_the_title() . '</li>' . '</br>';
				echo 'Event Date: ' . date( 'd.m.y', intval( get_post_meta( $post->ID, 'events-date', true ) ) ) . '</br>';
				echo 'Event Status: ' . get_post_meta( $post->ID, 'events-status', true );
			}
		} else {
			echo 'Events not found';
		}
		/* Restore original Post Data */
		wp_reset_postdata();

	}

	public function update( $new_instance, $old_instance ) {
		return parent::update( $new_instance, $old_instance ); // TODO: Change the autogenerated stub
	}
}

function events_register_widget() {
	register_widget( 'events_widget' );
}
add_action( 'widgets_init', 'events_register_widget' );